# /srv/jaroslav.tech/docker-compose.yml
# FINAL WORKING VERSION

services:
  app:
    build: .
    container_name: jaroslav_tech_app
    restart: unless-stopped
    # The 'command' directive is now removed.
    # The container will use the CMD from its Dockerfile.
    volumes:
      - .:/home/app
    expose:
      - "8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
      - proxy-net

  db:
    image: postgres:15-alpine
    container_name: jaroslav_tech_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
    networks:
      - default

volumes:
  postgres_data:

networks:
  proxy-net:
    external: true
