# File: /srv/jaroslav.tech/docker-compose.yml
# FINAL VERSION for the flat project structure

services:
  app:
    # Build using the Dockerfile in the current directory '.'
    build: .
    container_name: jaroslav_tech_app
    restart: unless-stopped
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      # Mount the entire current directory into the container
      - .:/home/app
    expose:
      - "8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
      - proxy-net

  db:
    image: postgres:15-alpine
    container_name: jaroslav_tech_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
    networks:
      - default

volumes:
  postgres_data:

networks:
  proxy-net:
    external: true